export default interface DataTypeCreateProductAdmin {
    image: File[],
    name: string,
    unit: string,
    categoryId: string,
    description: string,
    productCode: string,
    supplierId: string,
    colorId: string,
    sizeId: string,
    materialId: string,
    brandId: string,
    dimension: string,
    weight: number,
}